# https://taskfile.dev
# To enable experimental features
# export TASK_X_FEATURE=1
# export TASK_X_REMOTE_TASKFILES=1
# https://taskfile.dev/docs/experiments/remote-taskfiles

version: "3"
dotenv: [".env", ".env.example", "{{.HOME}}/.env"]

includes:
  env:
    taskfile: https://raw.githubusercontent.com/lwmacct/251207-task-remote/refs/heads/main/.task/env.yml
    optional: true
    flatten: true

  git:
    taskfile: https://raw.githubusercontent.com/lwmacct/251207-task-remote/refs/heads/main/.task/git.yml
    optional: true

  go:
    taskfile: https://raw.githubusercontent.com/lwmacct/251207-task-remote/refs/heads/main/.task/go.yml
    optional: true

  cmd:
    taskfile: .task/cmd.yml
    optional: true
